### ISSUE TITLE
links to the main GAP manual are broken in the html manual

### ISSUE THREAD

**Issue by dimpase** [gap-packages/ace#10]
A typical such link looks as `<a href="badlink:ref:Options Stack">Options Stack</a>`

(e.g. in Sect. 4 there are many such links)

**Comment by fingolfin** [comment]
This was a problem with the release wrapping, and will be automatically fixed in the next release.

**Comment by fingolfin** [comment]
This is now fixed thanks to the release of ACE 5.3
