### ISSUE TITLE
increase the default workspace to 10^8

### ISSUE THREAD

**Issue by dimpase** [gap-packages/ace#12]
20 years ago 10^6 (4 Megabytes) was a meaningful workspace setting, nowadays even a mobile phone can easily take 10^7 or 10^8.

**Comment by fingolfin** [comment]
10^8 amounts to 400 MB on a 32bit system, and 800 MB on a 64bit system. While it'd be fine for me, I wonder 

@gregg0 what do you think? I already looked into making the change, it's easy enough. Only question s what value you to use: 10^8, or 10^7, or anything in between (e.g. 2^24, for about 128 MB on a 64 bit system; or 2^25 for 256 MB) ...

**Comment by gregg0** [comment]
Dear Max


I think you're right ... the default should be increased.

The current default made sense 15-20 years ago, when RAM and diskspace was measured in MB.

Now we measure in GB, and nearly TB.

So the default ought to be at least 10^8.

The question of decimal or binary is only an issue if one departs from 10 powers being a multiple

of 3, and 2 powers being a multiple of 10.

i.e. 10^3 approx= 2^10

Is making the default 10^9 too much?


Regards,

Greg

________________________________

**Comment by fingolfin** [comment]
I went with 10^8 for now -- going to 10^9 would have meant a default workspace size of 8 GB, which may be a bit much for some people with not that powerful hardware. But of course we can revisit this and increase it again another day.
