### ISSUE TITLE
ACE under Cygwin

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/ace#13]
Currently in the GAP master branch, when ACE binaries are compiled under Cygwin, and then GAP distribution with them is tested on a Cygwin-free machine (GAP started with `bin/gap.bat`), loading ACE results in the following error:

```
The system cannot find the path specified.
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `+' on 2 arguments
The 1st argument is 'fail' which might point to an earlier problem
 at /proc/cygdrive/C/gap-4.9.0/lib/methsel2.g:250 called from
<function "HANDLE_METHOD_NOT_FOUND">( <arguments> )
 called from read-eval loop at /proc/cygdrive/C/gap-4.9.0/pkg/ace-5.2/gap/ace.gi:47
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk>
```
This has been reported first in https://github.com/gap-system/gap/issues/1820. For now, in the GAP distribution for Windows, I will remove `ace-*/bin` directory to ensure that `LoadAllPackages();` works, but it will be nice to fix this in the long run to ensure that `LoadAllPackages();` does not result in a break loop on Windows without any provisional arrangements.

One possible fix could be to use `ExternalFilename` like GRAPE package does, but see https://github.com/gap-system/gap/issues/2023 regarding this.

**Comment by fingolfin** [comment]
I pushed a commit which changes the code to use `ExternalFilename`, but I have no means to test it on Cygwin.

**Comment by alex-konovalov** [comment]
This doesn't help:
```
'C:\cygwin\home\alexk\GITREPS\gap\pkg\ace\bin\i686-pc-cygwin-default32-kv6\ace' is not recognized as an internal or external command,
operable program or batch file.
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `+' on 2 arguments
The 1st argument is 'fail' which might point to an earlier problem
 at /proc/cygdrive/C/cygwin/home/alexk/GITREPS/gap/lib/methsel2.g:249 called from
<function "HANDLE_METHOD_NOT_FOUND">( <arguments> )
 called from read-eval loop at /proc/cygdrive/C/cygwin/home/alexk/GITREPS/gap/pkg/ace/gap/ace.gi:47
type 'quit;' to quit to outer loop
brk>
```

**Comment by fingolfin** [comment]
There is nothing I can do about this. Patches welcome.

**Comment by fingolfin** [comment]
I wonder if (part of) the problem is the `.exe` suffix: the `ace` binary doesn't have one, I think, and we explicitly copy it to `bin/GAPARCH/ace` -- perhaps on cygwin we need to copy it to `bin/GAPARCH/ace.exe` instead?

Alas, I still can't help it because I have no convenient way to work on Windows.

**Comment by gregg0** [comment]
Dear Max

I've got no clue on this one (since I'm back to not having Windows)
... I probably should have
    ... at Curtin they work mostly on Windows
    ... so I had the environment to experiment
        ... but in 2017 and since, I would have had difficulty finding the time.

I think your guess is probably right on, since Windows would indeed look
for the .exe extension.

Regards,
Greg


________________________________

**Comment by alex-konovalov** [comment]
It's now loadable under Windows in GAP 4.11.1.
