### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/ace#2]
It seems the ACE homepage is dead, at least I couldn't find it anymore. More generally, at least the following links which occur in various files seem to be broken our outdated
* <http://www.csee.uq.edu.au/~cram> and <http://www.csee.uq.edu.au/~cram/ce.html> are dead
* <http://www.itee.uq.edu.au/~havas> redirects to <http://staff.itee.uq.edu.au/havas/>
* <http://www.csee.uq.edu.au/~havas/cdmc.html> is dead
* <http://www.itee.uq.edu.au/~cram/ce.html> is dead
* ...

**Comment by gregg0** [comment]
So in the banner ... we need to lose ~ for George and replace www by staff.
For Colin, he seems to still be at UQ as honorary staff with email address: cram@itee.uq.edu.au

csee was replaced by itee back in about 2000.
________________________________________

**Comment by gregg0** [comment]
ACE 3.001 is now available from George Havas's site: http://staff.itee.uq.edu.au/havas/
Colin Ramsay no longer has a UQ website. So all references to him, except where to download ACE now refer to: cram@itee.uq.edu.au
And all ACE-related websites have been replaced by just the one: http://staff.itee.uq.edu.au/havas/
________________________________________
From: Gregory Gamble
Sent: Friday, March 04, 2016 2:40 AM
To: gap-packages/ace
Subject: RE: [ace] Dead links (#2)

So in the banner ... we need to lose ~ for George and replace www by staff.
For Colin, he seems to still be at UQ as honorary staff with email address: cram@itee.uq.edu.au

csee was replaced by itee back in about 2000.
________________________________________

**Comment by fingolfin** [comment]
Fixed by @gregg0
