### ISSUE TITLE
Html-based help search doesn't work for appendices

### ISSUE THREAD

**Issue by RussWoodroofe** [gap-packages/ace#23]
GAP's help system seems to be confused by ACE's several appendices, and topics in the appendices do not load correctly on a search from within GAP when display is set to html.  (Other topics load fine, and you can then navigate to the appendices.)

You can reproduce the problem by 
gap> SetHelpViewer("browser");
gap> ?The meaning of ace

I'm testing on GAP 4.11.0 here, but I don't believe that anything has changed recently.

**Comment by RussWoodroofe** [comment]
Investigating a little more, it looks like the appendices A, B, etc are labeled as chapters 7, 8, etc in the manual.six file.  Relabeling them correctly in that file confuses GAP when it tries to load.  Linking e.g CHAP00A.htm to CHAP007.htm seems to fix the problem.

**Comment by RussWoodroofe** [comment]
Appears to be a larger problem affecting all packages using TeX-based help and appendices: as near as I can tell, these are CRISP and Irredsol.

**Comment by alex-konovalov** [comment]
@RussWoodroofe maybe report in the GAP repository, with links to this issue (and similar issues in other packages, if any?)

**Comment by RussWoodroofe** [comment]
Reported at https://github.com/gap-system/gap/issues/4430 .  Closing here.
