### ISSUE TITLE
5.6.2 tarball has funky Apple stuff in it

### ISSUE THREAD

**Issue by dimpase** [gap-packages/ace#35]
On Linux, GNU tar 1.34:
```
$ wget https://github.com/gap-packages/ace/releases/download/v5.6.2/ace-5.6.2.tar.gz
$ tar xf ace-5.6.2.tar.gz 
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.lastuseddate#PS'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.TextEncoding'
$
```

**Comment by dimpase** [comment]
I can fix it myself if you promote me to a maintainer (hey, I am an active user of ACE, after all, cf. https://arxiv.org/abs/1603.01710)

**Comment by fingolfin** [comment]
But what is the problem? Is it just that it violates a desire for tidiness or is there an actual problem?

**Comment by dimpase** [comment]
> desire for tidiness
this,  as well as possible breakage of (CI, or not) scripts, which might check that `tar` does not complain.
