### ISSUE TITLE
citing ACE GAP package

### ISSUE THREAD

**Issue by dimpase** [gap-packages/ace#4]
I had to create the following bibtex in order to be able to cite it in a paper:
@manual{acegap,
  author =    {Greg Gamble and Alexander Hulpke and George Havas and Colin Ramsay and Max Horn}, 
  title =     {{GAP} {P}ackage {ACE}},
  year =      {1998--},
  note = {(\url{http://gap-packages.github.io/ace/})},
}

Perhaps you might consider putting it somewhere, say in README?

**Comment by alex-konovalov** [comment]
@dimpase I suggest to cite the version that was used, too, for example, call `Cite("ace");` from GAP and then adjust it to your needs:

```
gap> Cite("ace");
Please use one of the following samples
to cite ace version from this installation

Text:

[GHHRH16]  Gamble,  G.,  Hulpke,  A.,  Havas,  G.,  Ramsay, C. and Horn, M., ACE, Advanced Coset Enumerator, Version 5.2 (2016), (Refereed GAP
package), https://gap-packages.github.io/ace.

HTML:

<p class='BibEntry'>
[<span class='BibKey'>GHHRH16</span>]   <b class='BibAuthor'>Gamble, G., Hulpke, A., Havas, G., Ramsay, C. and Horn, M.</b>,
 <i class='BibTitle'>ACE, Advanced Coset Enumerator,
         Version 5.2</i>
 (<span class='BibYear'>2016</span>)<br />
(<span class='BibNote'>Refereed GAP package</span>),
<span class='BibHowpublished'><a href="https://gap-packages.github.io/ace">https://gap-packages.github.io/ace</a></span>.
</p>

BibXML:

<entry id="ACE5.2"><misc>
  <author>
    <name><first>Greg</first><last>Gamble</last></name>
    <name><first>Alexander</first><last>Hulpke</last></name>
    <name><first>George</first><last>Havas</last></name>
    <name><first>Colin</first><last>Ramsay</last></name>
    <name><first>Max</first><last>Horn</last></name>
  </author>
  <title><C>ACE</C>, Advanced Coset Enumerator,
         <C>V</C>ersion 5.2</title>
  <howpublished><URL>https://gap-packages.github.io/ace</URL></howpublished>
  <month>Mar</month>
  <year>2016</year>
  <note>Refereed GAP package</note>
  <keywords>coset enumeration; Felsch strategy; HLT strategy; coset table; index; maxcosets; activecosets</keywords>
</misc></entry>

BibTeX:

@misc{ ACE5.2,
  author =           {Gamble, G. and Hulpke, A. and Havas, G. and Ramsay, C. and Horn, M.},
  title =            {{ACE}, Advanced Coset Enumerator, {V}ersion 5.2},
  month =            {Mar},
  year =             {2016},
  note =             {Refereed GAP package},
  howpublished =     {\href {https://gap-packages.github.io/ace} {\texttt{https://gap-packages.github.io/}\discretionary {}{}{}\texttt{ace}}},
  keywords =         {coset enumeration; Felsch strategy; HLT strategy; coset table; index; maxcosets; activecosets},
  printedkey =       {GHHRH16}
}

gap> 
```

**Comment by dimpase** [comment]
Ah, OK, I didn't know about Cite(), or forgot... Thanks!

**Comment by gregg0** [comment]
Dear  Alex

Does your answer to Dima solve everything, or is there still something I should do in ACE 5.3? The way I read it, your answer was complete (thanks).

Regards,
Greg
________________________________________

**Comment by dimpase** [comment]
I have closed this issue, meaning that Alex's answer was right on target. 

I do have complaints about using ACE as a replacement for GAP's coset enumeration, as it's either not well-documented, or missing functionality (or both). Mostly, I do not want to be thrown into an brk> loop just because there is no way to specify ACE parameters before starting coset enumeration in the usual GAP way.

**Comment by alex-konovalov** [comment]
It will be still a good idea to provide a suggestion how to cite ACE in its manual and in the README. This information seems missing, so I am reopening this issue.

**Comment by dimpase** [comment]
I agree that ideally one should not need a GAP installation to get the citation info.
Perhaps the output of Cite() can be embedded into the docs generated?

**Comment by fingolfin** [comment]
I disagree with this idea: If you are using ACE, you should have it installed, and can thus use `Cite`. If you do not have ACE installed, you are not using it. Moreover, I'd say the majority of package do not contain this explicit citation information. 

That said, I probably would merge a sensible PR adding this information, *provided* it does not hardcode versions or other stuff that needs to be manually updated with each release. 

But I don't think it makes sense to keep this issue open as a "feature request" as long as nobody on the ACE team (Greg and me) has any intention to act on this.

However, what I now *did* do was to update the website to use the latest GithubPagesForGAP template, so that https://gap-packages.github.io/ace/ now has some cite information which is automatically updated with each release.

**Comment by alex-konovalov** [comment]
> However, what I now did do was to update the website to use the latest GithubPagesForGAP template, so that https://gap-packages.github.io/ace/ now has some cite information which is automatically updated with each release

That resolves it from my POW, thanks @fingolfin

**Comment by alex-konovalov** [comment]
P.S. I do think that "ideally one should not need a GAP installation to get the citation info" as well. There may be needs to cite software without using the software, e.g. in an review paper, or while describing one's software and mentioning other similar packages in the overview. Of course, now the "citing" on the webpages suits that purpose perfectly.
