### ISSUE TITLE
specifying options in advance? 

### ISSUE THREAD

**Issue by dimpase** [gap-packages/ace#9]
The only way described in the docs to use ACE as the default TC program does not mention
how to do it with non-default options, which is often needed. Indeed, after
```
LoadPackage("ACE");
TCENUM:=ACETCENUM;
...
G:=...
H:=...
r:=FactorCosetAction(G,H);
```
one can easily run out of space, and do
```
brk> SetACEOptions(:workspace:=10^9); # say, this much
brk> return;
```
to complete the task, but this is a hassle. (It's somewhere not even in the init scrips in `pkg/ace-5.2/` how to change this option). 

Note that the command `SetACEOptions()` does not work before the start of the enumeration. One gets
```
gap> SetACEOptions(:workspace:=10^9);
#I  No interactive ACE sessions are currently active
Error, no currently active interactive ACE sessions called from
...
```

**Comment by fingolfin** [comment]
Actually, the manual does describe how to do this: chapter 4 is all about this, and the examples also show it:
```
r:=FactorCosetAction(G,H : workspace:=10^9);
```

**Comment by dimpase** [comment]
On 17 Apr 2017 5:32 p.m., "Max Horn" <notifications@github.com> wrote:

Actually, the manual does describe how to do this: chapter 4 is all about
this, and the examples also show it:

r:=FactorCosetAction(G,H : workspace:=10^9);

—


Thanks. However, one has to read all the way to sect 4 to find this. It
ought to be mentioned in sect 1.1 already; instead, sect 1.1 sends you to
sect. 5.

I'll see if I could do a pull request to fix this in the docs.

You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gap-packages/ace/issues/9#issuecomment-294522557>, or mute
the thread
